<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}" data-theme="dark">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ $report->label ?? 'Field Operations Report' }} — CMIH Africa</title>
    <link rel="icon" href="{{ asset('favicon.ico') }}" sizes="any">
    <link rel="icon" type="image/png" sizes="32x32" href="{{ asset('images/logo/favicon.png') }}">
    <link rel="apple-touch-icon" sizes="192x192" href="{{ asset('images/logo/icon-192.png') }}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Sora:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    @vite(['resources/css/app.css', 'resources/js/app.js'])
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    @if($report->section('show_tracking'))
    <script>
        function initGoogleMaps() { window._googleMapsReady = true; window.dispatchEvent(new Event('google-maps-ready')); }
    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key={{ env('GOOGLE_MAPS_API_KEY') }}&callback=initGoogleMaps" async defer></script>
    @endif
    <style>
        #report-map { height: 480px; width: 100%; border-radius: 1rem; overflow: hidden; }
        .stat-card { transition: transform 0.2s ease, box-shadow 0.2s ease; }
        .kpi-glow-red   { box-shadow: 0 0 20px rgba(220,38,38,0.15); }
        .kpi-glow-green { box-shadow: 0 0 20px rgba(34,197,94,0.15); }
        .kpi-glow-blue  { box-shadow: 0 0 20px rgba(59,130,246,0.15); }
    </style>
</head>
<body class="bg-brand-black font-sans antialiased text-brand-white">

    <div class="min-h-screen bg-inked py-10 px-4 sm:px-6 lg:px-8">
        <div class="max-w-6xl mx-auto space-y-8">

            <!-- Header -->
            <div class="glass-panel rounded-2xl p-6 border border-brand-white/10 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
                <div class="flex items-center gap-3">
                    <x-application-logo class="h-8 w-auto" />
                    <div>
                        <p class="text-[10px] uppercase tracking-[0.25em] text-brand-red font-bold">Client Dashboard</p>
                        <h1 class="text-xl font-bold font-display text-brand-white">{{ $report->label ?? 'Field Activity Report' }}</h1>
                    </div>
                </div>
                <div class="text-right">
                    <span class="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full bg-brand-red/10 border border-brand-red/25 text-brand-red text-xs font-bold">
                        ⏳ Link Expires: {{ $report->expires_at->format('h:i A d M') }}
                    </span>
                    <p class="text-[10px] text-brand-ash mt-1">Generated by {{ $report->creator->name ?? 'CMIH Admin' }}</p>
                </div>
            </div>

            <!-- Overview tab -->
            @if($report->section('show_overview'))
            <div class="grid grid-cols-1 sm:grid-cols-3 gap-5">
                <div class="stat-card kpi-glow-green glass-panel rounded-2xl p-5 border border-brand-white/10">
                    <p class="text-[10px] uppercase tracking-widest text-brand-ash mb-2">Active Field Agents</p>
                    <p class="text-3xl font-display text-green-400">{{ $data['total_active'] }}</p>
                </div>
                <div class="stat-card kpi-glow-blue glass-panel rounded-2xl p-5 border border-brand-white/10">
                    <p class="text-[10px] uppercase tracking-widest text-brand-ash mb-2">Key Distributors</p>
                    <p class="text-3xl font-display text-blue-400">{{ $data['total_kds'] }}</p>
                </div>
                <div class="stat-card kpi-glow-red glass-panel rounded-2xl p-5 border border-brand-white/10">
                    <p class="text-[10px] uppercase tracking-widest text-brand-ash mb-2">Agent Clock-Ins Today</p>
                    <p class="text-3xl font-display text-brand-red">{{ $data['today_clockins'] }}</p>
                </div>
            </div>

            <div class="glass-panel rounded-2xl border border-brand-white/10 overflow-hidden">
                <div class="px-5 py-4 border-b border-brand-white/10">
                    <p class="text-xs uppercase tracking-widest text-brand-ash">Field Agent Clock-In Detail</p>
                    <p class="text-xs text-brand-ash mt-0.5">Last 30 days by merchandiser, KD, weekday, time, and clock-in type.</p>
                </div>
                <div class="overflow-x-auto">
                    <table class="w-full min-w-[1100px] text-sm border-separate border-spacing-x-3 border-spacing-y-2">
                        <thead>
                            <tr>
                                <th class="px-4 py-3 text-left text-[10px] uppercase tracking-widest text-brand-ash">Merchandiser</th>
                                <th class="px-4 py-3 text-left text-[10px] uppercase tracking-widest text-brand-ash">KD</th>
                                <th class="px-4 py-3 text-left text-[10px] uppercase tracking-widest text-brand-ash">Supervisor</th>
                                <th class="px-4 py-3 text-center text-[10px] uppercase tracking-widest text-brand-ash">Days Worked</th>
                                <th class="px-4 py-3 text-left text-[10px] uppercase tracking-widest text-brand-ash">Recent Weekdays / Times / Types</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse($data['agent_clock_details'] as $agent)
                                <tr>
                                    <td class="rounded-l-xl border-y border-l border-brand-white/10 bg-brand-white/[0.03] px-4 py-3 font-semibold text-brand-white">{{ $agent['name'] }}</td>
                                    <td class="border-y border-brand-white/10 bg-brand-white/[0.03] px-4 py-3 text-brand-ash">{{ $agent['kd'] }}</td>
                                    <td class="border-y border-brand-white/10 bg-brand-white/[0.03] px-4 py-3 text-brand-ash">{{ $agent['supervisor'] }}</td>
                                    <td class="border-y border-brand-white/10 bg-brand-white/[0.03] px-4 py-3 text-center font-bold text-green-400">{{ $agent['total_days_worked'] }}</td>
                                    <td class="rounded-r-xl border-y border-r border-brand-white/10 bg-brand-white/[0.03] px-4 py-3">
                                        <div class="flex flex-wrap gap-2">
                                            @forelse($agent['clockins'] as $clock)
                                                <span class="rounded-lg border border-brand-white/10 bg-brand-black/40 px-2 py-1 text-[10px] text-brand-white/75">
                                                    {{ $clock['weekday'] }} {{ $clock['date'] }} · {{ $clock['time'] }} · {{ $clock['type'] }} · {{ $clock['outlet'] }}
                                                </span>
                                            @empty
                                                <span class="text-brand-ash">No clock-ins in the last 30 days.</span>
                                            @endforelse
                                        </div>
                                    </td>
                                </tr>
                            @empty
                                <tr><td colspan="5" class="px-5 py-6 text-center text-brand-ash">No merchandiser clock-in detail available.</td></tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>
            </div>

            @if(($data['supervisor_clock_details'] ?? collect())->isNotEmpty())
            <div class="glass-panel rounded-2xl border border-brand-white/10 overflow-hidden">
                <div class="px-5 py-4 border-b border-brand-white/10">
                    <p class="text-xs uppercase tracking-widest text-brand-ash">Supervisor Clock-In Detail</p>
                    <p class="text-xs text-brand-ash mt-0.5">Supervisor assignments and recent supervisor clock-ins where available.</p>
                </div>
                <div class="overflow-x-auto">
                    <table class="w-full min-w-[900px] text-sm">
                        <thead>
                            <tr class="border-b border-brand-white/10 bg-brand-white/3">
                                <th class="px-5 py-3 text-left text-[10px] uppercase tracking-widest text-brand-ash">Supervisor</th>
                                <th class="px-5 py-3 text-center text-[10px] uppercase tracking-widest text-brand-ash">Assigned Merchandisers</th>
                                <th class="px-5 py-3 text-left text-[10px] uppercase tracking-widest text-brand-ash">Recent Weekdays / Times / Types</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($data['supervisor_clock_details'] as $supervisor)
                                <tr class="border-b border-brand-white/5">
                                    <td class="px-5 py-3 font-semibold text-brand-white">{{ $supervisor['name'] }}</td>
                                    <td class="px-5 py-3 text-center font-bold text-blue-400">{{ $supervisor['assigned_merchandisers'] }}</td>
                                    <td class="px-5 py-3">
                                        <div class="flex flex-wrap gap-2">
                                            @forelse($supervisor['clockins'] as $clock)
                                                <span class="rounded-lg border border-brand-white/10 bg-brand-black/40 px-2 py-1 text-[10px] text-brand-white/75">
                                                    {{ $clock['weekday'] }} {{ $clock['date'] }} · {{ $clock['time'] }} · {{ $clock['type'] }} · {{ $clock['outlet'] }}
                                                </span>
                                            @empty
                                                <span class="text-brand-ash">No supervisor clock-ins yet.</span>
                                            @endforelse
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
            @endif
            @endif

            <!-- Attendance Chart -->
            @if($report->section('show_attendance_chart'))
            <div class="glass-panel rounded-2xl p-5 border border-brand-white/10">
                <p class="text-xs uppercase tracking-widest text-brand-ash mb-4">📅 Daily Attendance — Last 7 Days</p>
                <canvas id="attendanceChart" height="100"></canvas>
            </div>
            @endif

            <!-- Live Map -->
            @if($report->section('show_tracking'))
            <div class="glass-panel rounded-2xl border border-brand-white/10 overflow-hidden">
                <div class="px-5 py-4 border-b border-brand-white/10">
                    <p class="text-xs uppercase tracking-widest text-brand-ash">🗺️ Live Agent Tracking</p>
                    <p class="text-xs text-brand-ash mt-0.5">Real-time status of active merchandisers on the field</p>
                </div>
                <div id="report-map"></div>
            </div>
            @endif

            <!-- Top Performers -->
            @if($report->section('show_top_performers'))
            <div class="glass-panel rounded-2xl border border-brand-white/10 overflow-hidden">
                <div class="px-5 py-4 border-b border-brand-white/10">
                    <p class="text-xs uppercase tracking-widest text-brand-ash">🏆 Top Performing Merchandisers</p>
                </div>
                <div class="overflow-x-auto">
                    <table class="w-full text-sm">
                        <thead>
                            <tr class="border-b border-brand-white/10 bg-brand-white/3">
                                <th class="px-5 py-3 text-left text-[10px] uppercase tracking-widest text-brand-ash">Agent Name</th>
                                <th class="px-5 py-3 text-left text-[10px] uppercase tracking-widest text-brand-ash">Key Distributor</th>
                                <th class="px-5 py-3 text-right text-[10px] uppercase tracking-widest text-brand-ash">Visits This Month</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse($data['top_performers'] as $m)
                            <tr class="border-b border-brand-white/5">
                                <td class="px-5 py-3 font-medium text-brand-white">{{ $m->name }}</td>
                                <td class="px-5 py-3 text-brand-ash text-xs">{{ $m->merchandiserKd->name ?? '—' }}</td>
                                <td class="px-5 py-3 text-right">
                                    <span class="inline-flex items-center px-2.5 py-0.5 rounded-full bg-green-500/10 text-green-400 text-xs font-bold">{{ $m->merchandiser_visits_count }}</span>
                                </td>
                            </tr>
                            @empty
                            <tr><td colspan="3" class="px-5 py-6 text-center text-brand-ash">No data available.</td></tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>
            </div>
            @endif

            <!-- Assets -->
            @if($report->section('show_assets'))
            <div class="glass-panel rounded-2xl border border-brand-white/10 overflow-hidden">
                <div class="px-5 py-4 border-b border-brand-white/10">
                    <p class="text-xs uppercase tracking-widest text-brand-ash">📁 POSM & Field Gear Inventory Deployments</p>
                </div>
                <div class="overflow-x-auto">
                    <table class="w-full text-sm">
                        <thead>
                            <tr class="border-b border-brand-white/10 bg-brand-white/3">
                                <th class="px-5 py-3 text-left text-[10px] uppercase tracking-widest text-brand-ash">Date</th>
                                <th class="px-5 py-3 text-left text-[10px] uppercase tracking-widest text-brand-ash">Agent</th>
                                <th class="px-5 py-3 text-left text-[10px] uppercase tracking-widest text-brand-ash">Item Name</th>
                                <th class="px-5 py-3 text-center text-[10px] uppercase tracking-widest text-brand-ash">Quantity</th>
                                <th class="px-5 py-3 text-left text-[10px] uppercase tracking-widest text-brand-ash">Location</th>
                                <th class="px-5 py-3 text-center text-[10px] uppercase tracking-widest text-brand-ash">Photo Proof</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse($data['assets'] as $asset)
                            <tr class="border-b border-brand-white/5">
                                <td class="px-5 py-3 text-brand-ash text-xs">{{ $asset->created_at->format('d M Y') }}</td>
                                <td class="px-5 py-3 font-medium text-brand-white text-xs">{{ $asset->createdBy->name ?? '—' }}</td>
                                <td class="px-5 py-3 text-brand-white text-xs">{{ $asset->item_name }}</td>
                                <td class="px-5 py-3 text-center text-xs font-bold text-blue-400">{{ $asset->quantity_out }}</td>
                                <td class="px-5 py-3 text-brand-ash text-xs">{{ $asset->location ?? '—' }}</td>
                                <td class="px-5 py-3 text-center">
                                    @if($asset->image_path)
                                    <a href="{{ Storage::url($asset->image_path) }}" target="_blank">
                                        <img src="{{ Storage::url($asset->image_path) }}" alt="Proof" class="w-10 h-10 rounded-lg object-cover border border-brand-white/10 hover:border-brand-red/50 transition">
                                    </a>
                                    @else
                                    <span class="text-brand-ash/40">—</span>
                                    @endif
                                </td>
                            </tr>
                            @empty
                            <tr><td colspan="6" class="px-5 py-6 text-center text-brand-ash">No field gear logs found.</td></tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>
            </div>
            @endif

            <!-- footer -->
            <div class="text-center text-xs text-brand-ash pt-6">
                <p>&copy; {{ date('Y') }} CMIH Africa Merchandising Portal. All rights reserved.</p>
            </div>

        </div>
    </div>

    @if($report->section('show_attendance_chart'))
    <script>
        const attCtx = document.getElementById('attendanceChart');
        if (attCtx) {
            new Chart(attCtx, {
                type: 'bar',
                data: {
                    labels: @json(array_keys($data['attendance_chart'])),
                    datasets: [{
                        data: @json(array_values($data['attendance_chart'])),
                        backgroundColor: 'rgba(220,38,38,0.55)',
                        borderColor: '#dc2626',
                        borderWidth: 1.5,
                        borderRadius: 6
                    }]
                },
                options: {
                    responsive: true,
                    maintainAspectRatio: true,
                    plugins: { legend: { display: false } },
                    scales: {
                        x: { grid: { color: 'rgba(255,255,255,0.05)' }, ticks: { color: 'rgba(255,255,255,0.5)' } },
                        y: { grid: { color: 'rgba(255,255,255,0.05)' }, ticks: { color: 'rgba(255,255,255,0.5)', stepSize: 1 }, beginAtZero: true }
                    }
                }
            });
        }
    </script>
    @endif

    @if($report->section('show_tracking'))
    <script>
        const mapLocations = @json($data['tracking_locations'] ?? []);

        function initMap() {
            const mapEl = document.getElementById('report-map');
            if (!mapEl) return;

            const map = new google.maps.Map(mapEl, {
                center: { lat: 5.6037, lng: -0.1870 },
                zoom: 11,
                mapTypeId: 'roadmap',
                styles: [
                    { elementType: 'geometry', stylers: [{ color: '#1a1a2e' }] },
                    { elementType: 'labels.text.fill', stylers: [{ color: '#8ec3b9' }] },
                    { elementType: 'labels.text.stroke', stylers: [{ color: '#1a3646' }] },
                    { featureType: 'water', stylers: [{ color: '#0e1626' }] }
                ]
            });

            const bounds = new google.maps.LatLngBounds();
            let hasPoints = false;
            const infoWindow = new google.maps.InfoWindow();

            mapLocations.forEach(m => {
                hasPoints = true;
                const color = m.clocked_in ? '#4ade80' : '#fbbf24';
                const bgColor = m.clocked_in ? '#16a34a' : '#b45309';

                const marker = new google.maps.Marker({
                    position: { lat: m.latitude, lng: m.longitude },
                    map: map,
                    icon: {
                        path: google.maps.SymbolPath.CIRCLE,
                        fillColor: bgColor,
                        fillOpacity: 0.85,
                        strokeColor: color,
                        strokeWeight: 2,
                        scale: 12
                    },
                    title: m.name
                });

                marker.addListener('click', () => {
                    infoWindow.setContent(`
                        <div style="font-family:'Sora',sans-serif; padding:8px 4px; min-width:180px; background:#0f0f0f; color:#fff;">
                            <p style="font-weight:700; font-size:13px; margin:0 0 4px;">${m.name}</p>
                            <p style="font-size:11px; color:rgba(255,255,255,0.6); margin:0;">⏱️ ${m.last_seen}</p>
                        </div>
                    `);
                    infoWindow.open(map, marker);
                });

                bounds.extend({ lat: m.latitude, lng: m.longitude });
            });

            if (hasPoints) {
                map.fitBounds(bounds);
                const listener = google.maps.event.addListener(map, 'idle', () => {
                    if (map.getZoom() > 14) map.setZoom(14);
                    google.maps.event.removeListener(listener);
                });
            }
        }

        window.addEventListener('load', () => {
            if (window._googleMapsReady) initMap();
            else window.addEventListener('google-maps-ready', initMap, { once: true });
        });
    </script>
    @endif

</body>
</html>
